/*
 * Demeter API
 * The first version of the Demeter API. 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fiwio.iot.demeter.api.model;

import com.google.gson.annotations.SerializedName;

/**
 * Input
 */
public class Input {
    @SerializedName("name")
    private String name = null;

    @SerializedName("value")
    private String value = null;

    public Input name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Input value(String value) {
        this.value = value;
        return this;
    }

    /**
     * Get value
     *
     * @return value
     **/
    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Input input = (Input) o;

        if (name != null ? !name.equals(input.name) : input.name != null) return false;
        return value != null ? value.equals(input.value) : input.value == null;

    }

    @Override
    public int hashCode() {
        int result = name != null ? name.hashCode() : 0;
        result = 31 * result + (value != null ? value.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return "com.fiwo.iot.demeter.api.api.model.Input{" +
                "name='" + name + '\'' +
                ", value='" + value + '\'' +
                '}';
    }
}

