/*
 * Demeter API
 * The first version of the Demeter API. 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fiwio.iot.demeter.api.model;

import com.google.gson.annotations.SerializedName;

/**
 * InlineResponse200
 */
public class InlineResponse200 {
    @SerializedName("data")
    private Demeter data = null;

    public InlineResponse200 data(Demeter data) {
        this.data = data;
        return this;
    }

    /**
     * Get data
     *
     * @return data
     **/
    public Demeter getData() {
        return data;
    }

    public void setData(Demeter data) {
        this.data = data;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        InlineResponse200 that = (InlineResponse200) o;

        return data != null ? data.equals(that.data) : that.data == null;

    }

    @Override
    public int hashCode() {
        return data != null ? data.hashCode() : 0;
    }
}

