@startuml

[*] --> closed
closed : valve closed
closed : no flowers irrigation
closed --> opening : onIrrigationStartime
opening --> closing : onOpeningAborted
opening --> open : onOpeningCounterDone
opening : valve drive on
opening : 20 seconds
open: valve open
open --> closing : onIrrigationDuration
closing --> closed

@enduml

@startuml

[*] --> closed
closed : all valves closed
closed --> irrigating_opening : onIrrigationStartime,\n onIrrigationManualStart

irrigating_opening --> irrigating : onOpeningDurationLapsed
irrigating_opening --> closing : onManualStop
irrigating_opening : valve drive on 20 seconds

irrigating: irrigation valve open
irrigating --> closing : onManualStop,\n onIrrigationDurationLapsed

closing --> closed : onClosingDurationLapsed
closing : valve drive on 20 seconds

closed --> barrel_filling_opening : onBarrelStarTime, \n onBarrelManualStart

barrel_filling_opening --> barrel_filling: onBarrelFillingDurationLapsed
barrel_filling_opening --> closing : onManualStop
barrel_filling : barrel filling valve open

barrel_filling --> closing : onBarrelFillingDurationLapsed,\n onSwimmingSensorActivated
@enduml
